name: Test asyncapi docgen

on: workflow_dispatch

env:
  FOO: generated
  FM: doc.frontMatter.yaml

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: generate md
        run: |
          npm install -g @asyncapi/generator
          ag doc.yaml @asyncapi/markdown-template@v1.2.1 -o generated -p frontMatter=$FM -p toc=false -p outFilename=doc.md

      - name: Print generated .md
        run: cat $FOO/doc.md
        
      - name: test humans with env var
        uses: actions/humans.txt@v1
        with:
          format: json
          

